name: Another CI
on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
    hello:
        runs-on: ubuntu-latest
        name: Hello
        steps:
            - run: echo "Hello"
