name: Getting changed packages
on: [pull_request]
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: alexshukel/get-changed-workspaces-action@change-action-output
              with:
                  package-path: app
                  base-ref: master
              id: testing_action
            - run: echo "${{ steps.testing_action.outputs.changed-packages-names }}"
            - run: echo "${{ steps.testing_action.outputs.changed-packages-paths }}"
