name: CI
on:
    pull_request:
        paths-ignore:
            - "packages/docs/**"
            - "examples/**"
        branches: [master]
    workflow_dispatch:
jobs:
    generate_matrix:
        name: Get changed packages
        runs-on: ubuntu-latest
        outputs:
            names: ${{ steps.changed_packages.outputs.names }}
            paths: ${{ steps.changed_packages.outputs.paths }}
            empty: ${{ steps.changed_packages.outputs.empty }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Find changed packages
              id: changed_packages
              uses: alexshukel/get-changed-workspaces-action@v1.0.0

    build:
        needs: [generate_matrix]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        name: Build, lint, and test ${{ matrix.name }} package on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["14.x", "16.x"]
                name: ${{ fromJson(needs.generate_matrix.outputs.names) }}
                os: [ubuntu-latest]

        steps:
            - run: echo "${{ matrix.name }}"
