name: Getting changed packages
on:
    pull_request:
        branches:
            - master
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: alexshukel/get-changed-packages-action@main
