name: Getting changed packages
on: [push]
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        outputs:
            workspaces: ${{ steps.testing_action.outputs.changed_workspaces }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: alexshukel/get-changed-workspaces-action@handle-push-action
              with:
                  package-path: app
                  base-ref: origin/master
              id: testing_action
            #            - run: echo "${{ steps.testing_action.outputs.changed_workspaces }}"
            - run: echo "Github ref is ${{ github.ref }}"
#            - run: echo "${{ github.action }} ${{ github.action_path }}"
#            - run: echo "${{ github.actor }} ${{ github.base_ref }}"
#            - run: echo "${{ github.event }} ${{ github.event_name }} ${{ github.event_path }}"
