name: Getting changed packages
on: push
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        outputs:
            workspaces: ${{ steps.testing_action.outputs.changed_workspaces }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: alexshukel/get-changed-workspaces-action@main
              id: testing_action
            - run: echo "${{ steps.testing_action.outputs.changed_workspaces }}"
            - run: echo "$GITHUB_REF ${{ github.ref }}"
