name: Getting changed packages
on:
    pull_request:
        branches:
            - master
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        outputs:
            workspaces: ${{ steps.testing_action.outputs.changed_workspaces }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - uses: alexshukel/get-changed-workspaces-action@use-map-workspaces
              id: testing_action
    another-job:
        runs-on: ubuntu-latest
        needs: [changed-packages]
        strategy:
            matrix:
                workspace: ${{ fromJson(needs.changed-packages.outputs.workspaces) }}
        steps:
            - run: echo "${{ matrix.workspace }}"
