name: Getting changed packages
on: [push]
jobs:
    changed-packages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: alexshukel/get-changed-workspaces-action@fix-getting-changed-packages
              with:
                  working-directory: app
                  base-ref: master
              id: testing_action
            - run: echo "${{ steps.testing_action.outputs.names }}"
            - run: echo "${{ steps.testing_action.outputs.paths }}"
