name: Getting changed packages
on:
    pull_request:
        paths-ignore:
            - docs/**
            - example/**
        branches: [master]
jobs:
    changed-packages:
        name: Get changed workspaces
        runs-on: ubuntu-latest
        outputs:
            names: ${{ steps.testing_action.outputs.names }}
        steps:
            - uses: actions/checkout@v2
            - uses: alexshukel/get-changed-workspaces-action@V1.0.0
              with:
                  working-directory: app
              id: testing_action
    build:
        needs: [get_changed_packages]
        if: ${{ !fromJson(needs.generate_matrix.outputs.empty) }}
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["14.x", "16.x"]
                os: [ubuntu-latest]
                package: ${{ fromJson(needs.get_changed_packages.outputs.names) }}
        steps:
            - run: echo ${{ matrix.package }}
